augmentation: true
batch_size: 128
checkpoint: lab1/ckpts/WideResNet/WideResNet14-2.pt
checkpoint_dir: lab1/ckpts/WideResNet
checkpoint_every: 20
comet_project: deep-learning-applications
config: lab1/configs/WideResNet/WideResNet14-2.yaml
dataset: CIFAR10
device: cuda:0
do_early_stopping: true
early_stopping:
  min_delta: 0.001
  patience: 7
experiment_name: WideResNet14-2
learning_rate: 0.01
log_every: 20
model: WideResNet
momentum: 0.9
num_blocks: 2
num_epochs: 100
num_filters: 16
num_workers: 4
scheduler:
  gamma: 0.95
  type: exponential
seed: 42
visualize: false
weight_decay: 0.0005
widen_factor: 2
