augmentation: true
batch_size: 128
checkpoint: lab1/ckpts/ResNet/ResNet56.pt
checkpoint_dir: lab1/ckpts/ResNet
checkpoint_every: 100
comet_project: deep-learning-applications
config: lab1/configs/ResNet/ResNet56.yaml
dataset: CIFAR10
device: cuda
do_early_stopping: true
early_stopping:
  min_delta: 0.002
  patience: 7
experiment_name: ResNet56
learning_rate: 0.01
log_every: 20
model: ResNet
momentum: 0.9
num_blocks: 9
num_epochs: 100
num_filters: 16
num_workers: 4
scheduler:
  gamma: 0.95
  type: exponential
seed: 42
skip: true
visualize: false
weight_decay: 0.0005
