augmentation: true
batch_size: 128
checkpoint: lab1/ckpts/ResNet/ResNet32.pt
checkpoint_dir: lab1/ckpts/ResNet
checkpoint_every: 20
comet_project: deep-learning-applications
config: lab1/configs/ResNet/ResNet32.yaml
dataset: CIFAR10
device: cuda:1
do_early_stopping: true
early_stopping:
  min_delta: 0.002
  patience: 4
experiment_name: ResNet32
learning_rate: 0.01
log_every: 20
model: ResNet
momentum: 0.9
num_blocks: 5
num_epochs: 100
num_filters: 16
num_workers: 4
scheduler:
  gamma: 0.95
  type: exponential
seed: 42
skip: true
visualize: false
weight_decay: 0.0005
