batch_size: 32
checkpoint_every: null
comet_project: deep-learning-applications
config: null
dataset: rotten_tomatoes
device: cuda
experiment_key: null
experiment_name: null
ft_setting: null
learning_rate: 0.0005
log_every: 10
max_length: 128
model: null
num_epochs: 10
num_workers: 4
seed: 42
visualize: false
checkpoint_dir: checkpoints
resume_checkpoint: null
