batch_size: 32
checkpoint: lab3/ckpts/distilbert_lora_q16
checkpoint_dir: lab3/ckpts
checkpoint_every: null
config_file: lab3/configs/distilbert_lora_q16.yaml
dataset: rotten_tomatoes
early_stopping:
  min_delta: 0.001
  patience: 7
experiment_name: distilbert_lora_q16
ft_setting:
  alpha: 32
  ftname: lora_q16
  lr_backbone: 1.0e-05
  lr_head: 5.0e-05
  rank: 16
  target_modules:
  - q_lin
  type: lora
  warmup: 0.05
  weight_decay: 0.001
log_every: 20
max_length: 128
model: distilbert
num_epochs: 50
num_workers: 4
seed: 42
visualize: false
