batch_size: 32
checkpoint: lab3/ckpts/distilbert_lora_q_8_rotten_tomatoes
checkpoint_dir: lab3/ckpts
checkpoint_every: null
config_file: lab3/configs/distilbert_lora_q_8_rotten_tomatoes.yaml
dataset: rotten_tomatoes
early_stopping:
  min_delta: 0.002
  patience: 5
experiment_name: distilbert_lora_q_8_rotten_tomatoes
ft_setting:
  alpha: 16
  ftname: lora_q_8
  lr_head: 0.0001
  rank: 8
  target_modules:
  - q_lin
  type: lora
learning_rate: 5.0e-05
log_every: 20
max_length: 128
model: distilbert
num_epochs: 50
num_workers: 4
seed: 42
visualize: false
warmup: 0.05
weight_decay: 0.01
