batch_size: 32
checkpoint_dir: checkpoints
checkpoint_every: null
comet_project: deep-learning-applications
config: experiments/distilbert_full.yaml
dataset: rotten_tomatoes
device: cuda
experiment_key: be4f9a4eb98d429086a8a813c1efd11f
experiment_name: distilbert_full
ft_setting:
  type: full
learning_rate: 5.0e-05
log_every: 10
max_length: 128
model: distilbert
num_epochs: 5
num_workers: 4
resume_checkpoint: checkpoints/e_05_distilbert_full
seed: 42
visualize: false
