batch_size: 128
checkpoint: lab4/ckpts/autoencoder.pt
checkpoint_dir: lab4/ckpts
checkpoint_every: 5
config: lab4/ckpts/autoencoder.yaml
dataset: CIFAR10
device: cuda:1
experiment_name: AutoEncoder
learning_rate: 0.0001
log_every: 20
model: AutoEncoder
num_epochs: 10
num_filters: 32
num_workers: 4
seed: 42
