augmentation: true
batch_size: 128
checkpoint: lab1/ckpts/CNN/SmallCNN.pt
checkpoint_dir: lab1/ckpts/CNN
checkpoint_every: 20
comet_project: deep-learning-applications
config: lab1/configs/CNN/SmallCNN.yaml
dataset: CIFAR10
device: cuda
do_early_stopping: false
experiment_name: SmallCNN
learning_rate: 0.01
log_every: 20
model: CNN
momentum: 0.9
num_blocks: 1
num_epochs: 20
num_filters: 16
num_workers: 4
scheduler:
  gamma: 0.95
  type: exponential
seed: 42
skip: false
visualize: false
weight_decay: 0.0005
